### ISSUE TITLE
Vytvorit stranku "kontakt" s formularem pro odesilani dotazu z webu (cca 2MD)

### ISSUE THREAD

**Issue by pkudela** [NLCR/registrdigitalizace#598]
Vytvorit novou stranky "kontakt", kde bude jednoduchy formular pro odeslani dotazu z webu. Prosim  @helena-oks specifikokvat co bude stranka kontakt obsahovat - nejaky text, jaka pole formulare, nazvy poli atd.

**Comment by lucka-pavlova** [comment]
Seznam polí, která mají být ve formuláři @helena-oks .

**Comment by helena-oks** [comment]
Přeneseno na gitlab jako issue 42.
