### ISSUE TITLE
Doplnit číslo vydání do zobrazení bibliografického záznamu v seznamu výsledků vyhledávání

### ISSUE THREAD

**Issue by zabak** [NLCR/registrdigitalizace#651]
Jedná se o MARC pole 250 podpole a

Je to potřeba v případech, kdy v daném roce vyšlo více vydání.

**Comment by zabak** [comment]
Jedná se i o doplnění údajů o čísle vydání z katalogů NK a MZK.

**Comment by lucka-pavlova** [comment]
Záznamy zobrazují pole vydání z MARCXML., není jako samostatné pole v Reliefu. Prosím o vyjádření MZK, jestli je to dostatečné.

**Comment by zabak** [comment]
V uživatelském rozhraní je to pomoc pro nás velká už v současné podobě. To, že teď není samostatné pole v Reliefu není problém, protože u sporných duplicit už jsme si vybudovali jiné kombinace identifikátorů, ale pokud by to byla úprava jednoduchá, tak to tam dejte aby to, co se zobrazuje v uživatelském zobrazení bylo i v administraci. U sporných věcí to smysl mít může.

**Comment by indrakm** [comment]
Jaká by byla pracnost toho zapracování?

**Comment by lucka-pavlova** [comment]
Ve vyhledávání funguje. Úprava Reliefu ke zvážení.

**Comment by zabak** [comment]
Tento problém považujeme za vyřešený, tak jak to je nám to stačí, toto issue je možné zavřít.
