### ISSUE TITLE
vyhledávání podle roků vydání - chyba rozšířeného vyhledávání 

### ISSUE THREAD

**Issue by helena-oks** [NLCR/registrdigitalizace#676]
Pokud je v poli rokvyd rozmezí let, např. u časopisů, nelze záznam vyhledat z rozšířeného vyhledávání z pole Rok vydání, a to ani při zadání jednoho roku z rozmezí (0 výsledků), ani zadáním celého obsahu pole (při zadání  např. "2011-2016" systém zatuhne). Při základním vyhledávání se to chová dobře. Mělo by to fungovat stejně při obou způsobech vyhledávání.

Příklad k testování: anatomie + čihák + 2011-2016

**Comment by lucka-pavlova** [comment]
@albertoh , prosím doplň náročnost

**Comment by albertoh** [comment]
Bude nutne upravit index a pridat do indexuru logiku pro zpracovani ruznych format dat

**Comment by helena-oks** [comment]
Přeneseno na interní git - issue 41.
