### ISSUE TITLE
Ztratil se záznam v reliefu v zobrazení podle názvů

### ISSUE THREAD

**Issue by helena-oks** [NLCR/registrdigitalizace#681]
![obrazek](https://user-images.githubusercontent.com/13746425/60864658-84ad8f00-a224-11e9-8038-a7db8c28b0d4.png)
![obrazek](https://user-images.githubusercontent.com/13746425/60864697-a0b13080-a224-11e9-8d28-2433f8e70c43.png)

**Comment by helena-oks** [comment]
Zprávy komisse pro soupis jsou v RD 2x (ABA013 a ABG001). V rejstříku podle názvů se zobrazí pouze záznam ABA013 (STK), záznam ABG001 se zobrazí pouze při hledání přes číslo záznamu. V uživatelském RD jsou záznamy oba, sloučeny podle ččnb.

**Comment by helena-oks** [comment]
Po novém importu záznamu ABG001 se to již zobrazuje správně, ale bylo by dobré zjistit, čím to mohlo být.

**Comment by SykoraLukas** [comment]
Snažím se zjisti příčiny

**Comment by helena-oks** [comment]
Situace se vyskytla znovu. Ženské listy digitalizovaly 2 knihovny, mnoho ročníků má ABA001 a jeden záznam má CBA001. V uživatelském rozhraní je to dobře vidět - viz obr.
![žnlisty1](https://user-images.githubusercontent.com/13746425/70426869-0c1d5980-1a74-11ea-8a41-9f6192dd65cf.jpg)

 V Reliefu se záznam CBA001 při hledání/řazení přes název nezobrazí, jde-li o celou databázi nebo o filtr na druh dokumentu. Při filtru na název se správně zobrazí jako poslední za záznamy ABA001. Nespolehlivé vyhledávání!

**Comment by helena-oks** [comment]
Přeneseno na interní git jako issue 12.
