### ISSUE TITLE
ServiceDesk - NK ČR - #IM 550 SD_R_329402

### ISSUE THREAD

**Issue by albertoh** [NLCR/registrdigitalizace#686]
Když mám v RD zaškrtnut "Test duplicit"
a do pole načtu čtečkou č.k. knihy - 
konkrétně 1003144274
tak se v poli změní na 19141918
a RD hlásí 0 záznamů.
Bez funkčního RD nelze pracovat.

**Comment by albertoh** [comment]
Zaznam s č.k. 1003144274 ma nazev "1914-1918 :".
V minulosti bylo pozadovano odstraneni znaky pri hledani titulu z nazvu vraceneho XServer Aleph.
V tomto pripade odstraneni vede k hledani 19141918, a to nema zadny vysledek.
Vratil jsem chovani zpatky, aby system hledal presnou shodu, a to "1914-1918 :"

**Comment by lucka-pavlova** [comment]
Prosím o otestování pana Ljubku

**Comment by JanMeritus** [comment]
uzaviram
